### ISSUE TITLE
extends audioWorkletNode

### ISSUE THREAD

**Issue by iooops** [bloom510/react-audio-worklet-example#1]
Hi, in this repo you didn't implement `class XXX extends window.audioWorkletNode` function in reactjs. I got an error when I was trying to do so.

Same issue I posted in create-react-app repo:
https://github.com/facebook/create-react-app/issues/6517

Have you got a solution for it?

**Comment by heyaphra** [comment]
Hi there,

I didn't extend the base AudioWorkletNode class because I had no reason to extend the functionality of the API as it stands. I was having a similar problem with the AudioWorkletProcessor interface which was solved by serving processors from the public directory.

You may find the following links useful:
https://hackernoon.com/implementing-audioworklets-with-react-8a80a470474
https://stackoverflow.com/questions/49971779/error-audioworkletnode-is-undefined-in-react-app

Since this seems to be more of a Web Audio question than an issue with this repository, I'm closing the issue.
